server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/callog-diet-db?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1  # HikariCP 유효성 검사 추가
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update  # 오직 테스트 환경에서만
      generate-ddl: true   # 오직 테스트 환경에서만
      show-sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
  #    lease-renewal-interval-in-seconds: 10 # 하트비트 간격(기본 30초)
  #    lease-expiration-duration-in-seconds: 30 # 만료 시간(기본 90초)
  client:
    # export
    register-with-eureka: true
    # import
    fetch-registry: true
    # 유레카 서버의 위치 주소
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/